# This is an import workflow to help you auto-import your repository every 5 minutes
 
name:
  Auto Import Cron Job
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Step to run the snyk api "import endpoint as part of the job
    steps:
    - name : Snyk API Import
      run: | 
        curl -X POST "https://api.snyk.io/api/v1/org/0d569e9a-dafe-40b5-a12e-24d711296a56/integrations/396ed33c-761c-4abb-92e4-a614c85b2b6f/import?page=1&perPage=1000&sortBy=severity&order=asc" \
        -H "Authorization: token 26ba134f-1768-44c9-ab75-32d4f2ff7cda" \
        -H "Content-Type: application/json; charset=utf-8" \
         -d '{
          "target":{
            "owner":"rchaib",
            "name":"juice-shop",
            "branch":"master"
          }
         }'
